"""empty message

Revision ID: 20682b97997d
Revises: 6c43c321d75c
Create Date: 2021-10-30 20:59:54.834243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20682b97997d'
down_revision = '6c43c321d75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
