"""empty message

Revision ID: 915cefce4bac
Revises: 20682b97997d
Create Date: 2021-10-31 18:29:56.373277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915cefce4bac'
down_revision = '20682b97997d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
