"""empty message

Revision ID: bc5f56cc2736
Revises: 0de2fa3ac04b
Create Date: 2021-11-11 18:22:30.963937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5f56cc2736'
down_revision = '0de2fa3ac04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('nam', sa.String(length=100), nullable=True))
    op.drop_index('ix_pokemon_name', table_name='pokemon')
    op.create_index(op.f('ix_pokemon_nam'), 'pokemon', ['nam'], unique=False)
    op.drop_column('pokemon', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pokemon_nam'), table_name='pokemon')
    op.create_index('ix_pokemon_name', 'pokemon', ['name'], unique=False)
    op.drop_column('pokemon', 'nam')
    # ### end Alembic commands ###
