"""empty message

Revision ID: bd97d984f033
Revises: bc5f56cc2736
Create Date: 2021-11-11 18:23:01.838412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd97d984f033'
down_revision = 'bc5f56cc2736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_index('ix_pokemon_nam', table_name='pokemon')
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    op.drop_column('pokemon', 'nam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('nam', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.create_index('ix_pokemon_nam', 'pokemon', ['nam'], unique=False)
    op.drop_column('pokemon', 'name')
    # ### end Alembic commands ###
